"""
07_make_macros.py  --  generate LaTeX macros and table fragments for the SpaceX paper.

Every number in the paper body flows from the results JSONs through this script (house rule:
no hand-typed numbers in the draft). Writes:
  paper/draft/output/numbers.tex                  (\newcommand macros for in-text numbers)
  paper/draft/output/tables/tab_implied.tex       (one-lever implied-value table body)
  paper/draft/output/tables/tab_physical.tex      (physical-implications table body)
  paper/draft/output/tables/tab_options.tex       (real-option values + sensitivities body)
  paper/draft/output/tables/tab_sumofparts.tex    (sum-of-parts vs market body)

Inputs: output/tables/*.json produced by the analysis scripts; one fresh stochastic run of the
base model for distribution percentiles (not stored in JSON).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from spacex_realoptions import FirmParams, simulate

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "paper" / "draft" / "output"
TABS = OUT / "tables"


def load(rel):
    return json.loads((ROOT / "output" / "tables" / rel).read_text())


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    TABS.mkdir(parents=True, exist_ok=True)

    inv = load("inverse_valuation.json")
    lay = load("layer3_acceptance.json")
    dec = load("decomposition.json")
    phys = load("physical_implications.json")
    freq = load("prospectus_term_frequency.json")

    # fresh stochastic distribution of the base model
    sto = simulate(FirmParams(), n=200_000, seed=2026, stochastic=True)
    eq = sto["equity"]

    L = ["% Auto-generated by 07_make_macros.py. Do not edit by hand."]

    def cmd(name, val):
        L.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    def T(x):                      # $M -> $T string, 2dp
        return f"{x/1e6:.2f}"

    def B(x):                      # $M -> $B string, 0dp with thin space
        return f"{x/1000:,.0f}".replace(",", "{,}")

    # --- headline / base model ---
    cmd("ipoT", "1.77")
    cmd("ipoShare", "135")
    # Prospectus financials (FWP, consolidated statements + risk factors): FY2025 total revenues
    # $18,674M; FY2025 net loss $(4,937)M ("We incurred net losses of $(4,937) million ... for the
    # year[] ended December 31, 2025").
    cmd("revLatestB", "18.7")
    cmd("netLossLatestB", "4.9")
    base_total = (dec["segments"]["Launch"] + dec["segments"]["Starlink"]
                  + dec["segments"]["xAI"] + dec["net_cash"])
    cmd("baseEquityT", T(base_total))
    # Conditional footnote: only when the two-decimal figure lands on a whole trillion, note that
    # the roundness is a coincidence of the calibration. Vanishes automatically if inputs change.
    if T(base_total).endswith(".00"):
        cmd("baseEquityRoundNote",
            f"\\footnote{{The round figure is a coincidence of the calibration rather than a "
            f"presentational choice: the four components sum to \\${base_total/1e6:.3f} trillion, "
            f"reported at the two decimals used for trillion-dollar figures throughout.}}")
    else:
        cmd("baseEquityRoundNote", "")
    cmd("basePerShare", f"{(eq.mean()/13091):.0f}")
    cmd("segLaunchB", B(dec["segments"]["Launch"]))
    cmd("segStarlinkB", B(dec["segments"]["Starlink"]))
    cmd("segXaiB", B(dec["segments"]["xAI"]))
    cmd("netCashB", B(dec["net_cash"]))
    cmd("eqPfiveT", T(np.quantile(eq, 0.05)))
    cmd("eqMedT", T(np.quantile(eq, 0.50)))
    cmd("eqPninefiveT", T(np.quantile(eq, 0.95)))
    cmd("probAboveIpoPct", f"{np.mean(eq > 1.8e6)*100:.0f}")

    # --- term frequencies ---
    c = freq["concepts"]
    cmd("freqAI", f"{c['AI / artificial intelligence']}")
    cmd("freqGrok", f"{c['Grok / xAI']}")
    cmd("freqCompute", f"{c['compute / data center']}")
    cmd("freqStarship", f"{c['Starship']}")
    cmd("freqMoon", f"{c['Moon / lunar']}")
    cmd("freqMars", f"{c['Mars']}")
    cmd("freqColony", f"{c['colony / colonization']}")
    cmd("freqMulti", f"{c['multiplanetary']}")
    ai_fam = c["AI / artificial intelligence"] + c["Grok / xAI"] + c["compute / data center"]
    mars_fam = c["Mars"] + c["colony / colonization"] + c["multiplanetary"] + c["Martian"]
    cmd("freqRatio", f"{ai_fam/mars_fam:.0f}")

    # --- options & sensitivities ---
    o = dec["options"]
    cmd("optDtcB", B(o["DTC"]))
    cmd("optStarshipB", B(o["Starship"]))
    cmd("optMarsB", f"{o['Mars']/1000:.1f}")
    cmd("optTotalB", B(o["DTC"] + o["Starship"] + o["Mars"]))
    # the option-claim parameters as used (single source: spacex_realoptions.py defaults)
    op = dec["option_params"]
    cmd("optDtcUnderlyingB", f"{op['DTC']['E_VDTC']/1000:.0f}")
    cmd("optDtcInvestB", f"{op['DTC']['invest']/1000:.0f}")
    cmd("optDtcTau", f"{op['DTC']['tau']:.0f}")
    cmd("optDtcSigma", f"{op['DTC']['sigma']:.2f}")
    cmd("optSsUnderlyingB", f"{op['Starship']['V_central']/1000:.0f}")
    cmd("optSsInvestB", f"{op['Starship']['invest']/1000:.0f}")
    cmd("optSsTau", f"{op['Starship']['tau']:.0f}")
    cmd("optSsSigma", f"{op['Starship']['sigma']:.2f}")
    cmd("optSsPtech", f"{op['Starship']['p_tech']:.2f}")
    cmd("optSsPtechPct", f"{op['Starship']['p_tech']*100:.0f}")
    # Launch-addressable pool ($B/yr): Congressional Research Service IF12900 (national-security
    # launch), NASA budget/OIG documents, commercial-constellation assessments (paper App. A.3).
    cmd("launchPoolLoB", "14")
    cmd("launchPoolHiB", "41")
    oc = dec["options_closed_form"]
    cmd("optDtcClosedB", f"{oc['DTC']/1000:.2f}")
    cmd("optDtcSimB", f"{o['DTC']/1000:.2f}")
    cmd("optDtcSeB", f"{oc['DTC_se']/1000:.2f}")
    cmd("optStarshipClosedB", f"{oc['Starship']/1000:.2f}")
    cmd("optStarshipSimB", f"{o['Starship']/1000:.2f}")
    cmd("optStarshipSeB", f"{oc['Starship_se']/1000:.2f}")
    sal = dec["salvage_sensitivity"]
    cmd("abandonZeroB", f"{sal['salvage $0B']['option_value']/1000:.1f}")
    cmd("abandonTenB", f"{sal['salvage $10B']['option_value']/1000:.1f}")
    cmd("abandonProbZeroPct", f"{sal['salvage $0B']['prob_abandon']*100:.0f}")
    cmd("abandonProbTenPct", f"{sal['salvage $10B']['prob_abandon']*100:.0f}")
    comp = dec["competition_sensitivity"]
    cmd("optTotalHaircutB", B(comp["haircut 30%"]["total_options"]))
    cmd("optStarshipHaircutB", f"{comp['haircut 30%']['Starship']/1000:.0f}")
    x = dec["xai_scenarios"]
    cmd("xaiFloorB", B(dec["venture_floor"]))
    cmd("xaiInfraB", B(x["infrastructure (16.5%)"]))
    cmd("xaiDamB", B(x["Damodaran-boundary (25%)"]))
    cmd("xaiWinB", B(x["winning model (30%)"]))
    cmd("groundedLoT", T(dec["grounded_total_range"][0]))
    cmd("groundedHiT", T(dec["grounded_total_range"][1]))
    cmd("premiumLoB", B(dec["ipo"] - dec["grounded_total_range"][1]))
    cmd("premiumHiB", B(dec["ipo"] - dec["grounded_total_range"][0]))

    # --- inverse (one lever at a time) ---
    imp = {r["parameter"]: r for r in inv["implied"]}
    cmd("implStarlinkRevB", f"{imp['Starlink 2036 revenue ($B)']['implied']:,.0f}")
    cmd("implXaiRevB", f"{imp['xAI 2036 revenue ($B)']['implied']:,.0f}")
    cmd("implLaunchRevB", f"{imp['Launch 2036 revenue ($B)']['implied']:,.0f}")
    cmd("implStarlinkMarginPct", f"{imp['Starlink terminal margin']['implied']*100:.0f}")
    cmd("implXaiMarginPct", f"{imp['xAI terminal margin']['implied']*100:.0f}")
    cmd("implWaccPct", f"{imp['WACC (terminal growth fixed)']['implied']*100:.2f}")
    cmd("implGrowthPct", f"{imp['Terminal growth (WACC fixed)']['implied']*100:.2f}")
    cmd("implRevScale", f"{imp['All 2036 revenues x k']['implied']:.2f}")
    cmd("waccGapPp", f"{(0.0825 - imp['WACC (terminal growth fixed)']['implied'])*100:.1f}")
    # xAI revenue required at the top of the winning-model margin band (0.40), from the panel-b curve
    curve = inv.get("panelB_curve", [])
    if curve:
        pt = min(curve, key=lambda r: abs(r["margin"] - 0.40))
        cmd("implXaiRevAtFortyB", f"{pt['rev_B']:,.0f}")

    # --- layer 3 ---
    # --- physical implications, duration, ERP ---
    Rsl = imp['Starlink 2036 revenue ($B)']['implied']
    Rxa = imp['xAI 2036 revenue ($B)']['implied']
    Rla = imp['Launch 2036 revenue ($B)']['implied']
    w_star = imp['WACC (terminal growth fixed)']['implied']
    cmd("physSubsBroadbandM", f"{Rsl*1e9/(66*12)/1e6:,.0f}")
    cmd("physSubsPremiumM", f"{Rsl*1e9/(120*12)/1e6:,.0f}")
    cmd("physLaunchesYr", f"{Rla*1e9/150e6:,.0f}")
    cmd("physLaunchesDay", f"{Rla*1e9/150e6/365:.1f}")
    cmd("physGwLo", f"{Rxa*1e9/5e6/1000:,.0f}")
    cmd("physGwHi", f"{Rxa*1e9/1e6/1000:,.0f}")
    cmd("erpPct", f"{(w_star-0.0456)*100:.1f}")
    # effective duration dlnV/dr and terminal-value share (recomputed, mirrors the audit)
    import copy as _copy
    def _v(w):
        q = _copy.deepcopy(FirmParams()); q.wacc = w
        return (simulate(q, n=1, seed=1, stochastic=False)["equity_mean"]
                + o["DTC"] + o["Starship"] + o["Mars"])
    eps = 0.0005
    cmd("durationYears", f"{-(np.log(_v(0.0825+eps))-np.log(_v(0.0825-eps)))/(2*eps):.0f}")
    p0 = FirmParams()
    t = np.arange(1, 12); disc_ = (1+p0.wacc)**(-t)
    taxp = 0.10+(0.25-0.10)*t/11
    pv_e = pv_t = 0.0
    for s in p0.segments:
        gex = (s.rev_target/s.rev0)**(1/11)-1
        R_ = s.rev0*(1+gex)**t; Rp_ = np.concatenate([[s.rev0], R_[:-1]])
        m_ = s.margin0+(s.margin_target-s.margin0)*t/11
        eb = m_*R_
        pv_e += float(((eb-taxp*np.maximum(eb,0)-np.maximum(R_-Rp_,0)/s.s2c)*disc_).sum())
        ft = eb[-1]*(1-0.25)*(1+p0.g_term)*(1-p0.g_term/p0.roic_term)
        pv_t += float(ft/(p0.wacc-p0.g_term)*disc_[-1])
    cmd("tvSharePct", f"{pv_t/(pv_e+pv_t)*100:.0f}")

    # --- xAI venture tail with/without the abandonment option (risk-profile exhibit) ---
    from venture_option import VentureParams, simulate_paths, value_with_option
    vp = VentureParams()
    Rv, muv, fcfv, tvv = simulate_paths(vp, 100_000, seed=2026)
    discv = (1 + vp.r) ** (-np.arange(1, vp.T + 1))
    vfull = (fcfv * discv[None, :]).sum(axis=1) + tvv * discv[-1]
    pathv, _, _ = value_with_option(vp, Rv, muv, fcfv, tvv)
    cmd("venturePFiveWithoutB", f"{abs(np.quantile(vfull, 0.05))/1000:.0f}")
    cmd("venturePFiveWithB", f"{abs(np.quantile(pathv, 0.05))/1000:.0f}")
    cmd("venturePOneWithoutB", f"{abs(np.quantile(vfull, 0.01))/1000:.0f}")
    cmd("venturePOneWithB", f"{abs(np.quantile(pathv, 0.01))/1000:.0f}")

    # --- back-of-envelope: abandonment option and the required return ---
    bote = dec["bote"]
    cmd("boteDelta", f"{abs(bote['dPdV']):.2f}")
    cmd("boteBetaRatio", f"{bote['beta_ratio']:.2f}")
    cmd("boteVenturePp", f"{bote['dr_venture_pp']:.1f}")
    cmd("boteVentureNewPct", f"{12 - bote['dr_venture_pp']:.1f}")
    cmd("boteFirmBp", f"{bote['dr_firm_bp']:.0f}")
    cmd("boteWeightPct", f"{bote['venture_weight']*100:.0f}")
    cmd("boteVentureValB", f"{bote['V_venture']/1000:.1f}")
    cmd("botePutValB", f"{bote['P_option']/1000:.1f}")

    gb = lay["grounded_box"]
    cmd("layAccPct", f"{lay['n_accepted']/lay['n_draws']*100:.1f}")
    cmd("gbPfiveT", T(gb["value_p5_p50_p95_max"][0]))
    cmd("gbMedT", T(gb["value_p5_p50_p95_max"][1]))
    cmd("gbPninefiveT", T(gb["value_p5_p50_p95_max"][2]))
    cmd("gbMaxT", T(gb["value_p5_p50_p95_max"][3]))
    cmd("gbSharePct", f"{gb['share_reaching_window']*100:.1f}")
    cmd("gbWaccMedPct", f"{gb['wacc_p5_p50_p95_among_reaching'][1]*100:.2f}")
    cmd("gbWaccSharePct", f"{gb['share_wacc_below_075_among_reaching']*100:.0f}")
    cmd("gbJointPct", f"{gb['share_joint_lowwacc_upperrev_among_reaching']*100:.0f}")

    (OUT / "numbers.tex").write_text("\n".join(L) + "\n")
    print(f"numbers.tex written ({len(L)-1} macros)")

    # ---------------- table fragments (tabular bodies only; captions live in main.tex) -----------
    def write(name, body):
        (TABS / name).write_text(body)
        print("wrote", TABS / name)

    # Implied-value table
    rows = [
        ("Starlink 2036 revenue (\\$B)", "120", f"{imp['Starlink 2036 revenue ($B)']['implied']:,.0f}", "above the supported range"),
        ("xAI 2036 revenue (\\$B)", "160", f"{imp['xAI 2036 revenue ($B)']['implied']:,.0f}", "$\\sim$30$\\times$ OpenAI's revenue"),
        ("Launch 2036 revenue (\\$B)", "40", f"{imp['Launch 2036 revenue ($B)']['implied']:,.0f}", "exceeds the addressable market"),
        ("Starlink terminal margin", "60\\%", f"{imp['Starlink terminal margin']['implied']*100:.0f}\\%", "no feasible value"),
        ("xAI terminal margin", "25\\%", f"{imp['xAI terminal margin']['implied']*100:.0f}\\%", "above every comparable"),
        ("WACC", "8.25\\%", f"{imp['WACC (terminal growth fixed)']['implied']*100:.2f}\\%", "inside estimation error"),
        ("Terminal growth", "4.56\\%", f"{imp['Terminal growth (WACC fixed)']['implied']*100:.2f}\\%", "exceeds the risk-free rate"),
        ("All 2036 revenues $\\times k$", "1.00", f"{imp['All 2036 revenues x k']['implied']:.2f}", "all above supported ranges"),
    ]
    body = ["\\begin{tabular}{lccl}", "\\toprule",
            "Lever & Base value & Implied by \\$1.77T & Assessment \\\\", "\\midrule"]
    body += [f"{a} & {b} & {c} & {d} \\\\" for a, b, c, d in rows]
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_implied.tex", "\n".join(body))

    # Physical-implications table (p-columns so long requirement text wraps inside the margins)
    body = ["\\begin{tabular}{@{}p{1.6cm}p{1.9cm}p{6.6cm}p{4.4cm}@{}}", "\\toprule",
            "Segment & Implied revenue & Physical requirement & Benchmark \\\\", "\\midrule"]
    keep = [0, 1, 3, 5, 6]   # broadband, premium, Starship-price launches, both AI rows
    bench = {
        0: "10.3M subscribers today",
        1: "$\\sim$100--400M unserved households",
        3: "12 flights total, 2023--2026",
        5: "US data-center load $\\sim$30--50 GW",
        6: "US generating capacity $\\sim$1{,}250 GW",
    }
    for i in keep:
        r = phys[i]
        req = (r["requirement"].replace("$", "\\$").replace("(", "").replace(")", "")
               .replace("subscribers at ", "subscribers, ").replace("launches/year at ", "launches/yr, ")
               .replace("AI compute at ", "AI compute, "))
        qty = r["quantity"].replace("(= ", "($\\approx$").replace("/day)", "/day)")
        body.append(f"{r['segment']} & {r['implied_rev'].replace('$', chr(92)+'$')} & {req}: {qty} & {bench[i]} \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    write("tab_physical.tex", "\n".join(body))

    # Options table
    body = ["\\begin{tabular}{lcc}", "\\toprule",
            "Real option & Value (\\$B) & Key sensitivity \\\\", "\\midrule",
            f"Starlink direct-to-cell (expansion) & {o['DTC']/1000:.1f} & premium $\\approx$ 0 (deep in the money) \\\\",
            f"Starship heavy-lift markets (expansion) & {o['Starship']/1000:.1f} & 30\\% haircut $\\to$ {comp['haircut 30%']['Starship']/1000:.1f} \\\\",
            f"Mars sovereign-program (expansion) & {o['Mars']/1000:.1f} & range 0.4--2.9; no competition haircut \\\\",
            f"xAI abandonment (downside) & {sal['salvage $0B']['option_value']/1000:.1f} & salvage \\$10B $\\to$ {sal['salvage $10B']['option_value']/1000:.1f} \\\\",
            "\\midrule",
            f"Total expansion options & {(o['DTC']+o['Starship']+o['Mars'])/1000:.1f} & 30\\% haircut $\\to$ {comp['haircut 30%']['total_options']/1000:.1f} \\\\",
            "\\bottomrule", "\\end{tabular}"]
    write("tab_options.tex", "\n".join(body))

    # Sum-of-parts table
    xhi = x["winning model (30%)"]
    body = ["\\begin{tabular}{lc}", "\\toprule", "Component & Value (\\$B) \\\\", "\\midrule",
            f"Launch + Starlink (core) & {B(dec['segments']['Launch']+dec['segments']['Starlink'])} \\\\",
            f"xAI segment (venture floor to winning scenario) & {B(dec['venture_floor'])} -- {B(xhi)} \\\\",
            f"Net cash including IPO proceeds & {B(dec['net_cash'])} \\\\",
            f"Expansion options & {B(o['DTC']+o['Starship']+o['Mars'])} \\\\",
            f"xAI abandonment option & {dec['salvage_sensitivity']['salvage $0B']['option_value']/1000:.1f} \\\\",
            "\\midrule",
            f"Grounded total & {B(dec['grounded_total_range'][0])} -- {B(dec['grounded_total_range'][1])} \\\\",
            f"IPO equity value & {B(dec['ipo'])} \\\\",
            f"Unexplained premium & {B(dec['ipo']-dec['grounded_total_range'][1])} -- {B(dec['ipo']-dec['grounded_total_range'][0])} \\\\",
            "\\bottomrule", "\\end{tabular}"]
    write("tab_sumofparts.tex", "\n".join(body))


if __name__ == "__main__":
    main()
