r"""
10_fig_price_path.py -- the share-price path and the expected return it implies, by trading day.

For each trading day's closing price in data/raw/post_ipo_series.json (offer + the listed closes),
invert the model -- operating inputs and the option layer held at base, exactly as in
04_inverse_valuation.py and 09_post_ipo_update.py -- for the discount rate that equates the model
value to that day's capitalization. The figure plots the closing price (left axis, rising) against
the implied expected return / cost of capital (right axis, falling), with the 8.25 percent baseline
marked; the gap between the two is the message: as the price runs above the offer the implied
return falls further below the baseline, and since no new operating information has arrived, each
step is a repricing of risk, not a cash-flow revision. The window ends at the first post-IPO
earnings release (after which new fundamentals break the hold-fundamentals-fixed inversion).

Writes paper/draft/output/figures/fig_price_path.pdf|png and paper/draft/output/pricepath.tex.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_valuation import implied_wacc as _solve          # noqa: E402
from spacex_realoptions import FirmParams                 # noqa: E402

SERIES = ROOT / "data" / "raw" / "post_ipo_series.json"
FIGS = ROOT / "paper" / "draft" / "output" / "figures"
OUT_TEX = ROOT / "paper" / "draft" / "output" / "pricepath.tex"
RF = 4.56
BASELINE = 8.25
NAVY, ORANGE = "#2E4057", "#E85D04"

_dec = json.loads((ROOT / "output" / "tables" / "decomposition.json").read_text())
OPT_BASE = sum(v for k, v in _dec["options"].items() if k != "Abandonment")


def implied_pct(cap_musd: float):
    w = _solve(FirmParams(), cap_musd, OPT_BASE)
    return w * 100 if w else None


def fmt(d: str) -> str:                                   # 2026-06-12 -> Jun 12
    return datetime.strptime(d, "%Y-%m-%d").strftime("%b %-d") if sys.platform != "win32" \
        else datetime.strptime(d, "%Y-%m-%d").strftime("%b ") + str(int(d[-2:]))


def main():
    d = json.loads(SERIES.read_text(encoding="utf-8-sig"))
    offer = float(d["offer_price"])
    sh = float(d["shares_m"])
    closes = d["closes"]

    labels = ["Offer"] + [fmt(c["date"]) for c in closes]
    prices = [offer] + [float(c["close"]) for c in closes]
    caps = [p * sh for p in prices]                       # $M
    wacc = [implied_pct(cap) for cap in caps]
    x = list(range(len(prices)))

    plt.rcParams.update({"font.size": 10.5, "figure.dpi": 120, "savefig.bbox": "tight"})
    fig, axp = plt.subplots(figsize=(8.0, 5.0))
    axr = axp.twinx()
    for ax in (axp, axr):
        ax.spines["top"].set_visible(False)

    # left: price
    axp.plot(x, prices, "-o", color=NAVY, lw=1.8, ms=6, zorder=3)
    axp.set_ylabel("Closing price (\\$ per share)", color=NAVY)
    axp.tick_params(axis="y", labelcolor=NAVY)
    for xi, p in zip(x, prices):
        axp.annotate(f"\\${p:.0f}", (xi, p), textcoords="offset points", xytext=(0, 8),
                     ha="center", fontsize=8.5, color=NAVY)

    # right: implied expected return
    axr.plot(x, wacc, "--s", color=ORANGE, lw=1.8, ms=6, zorder=3)
    axr.set_ylabel("Implied expected return (cost of capital), percent", color=ORANGE)
    axr.tick_params(axis="y", labelcolor=ORANGE)
    axr.axhline(BASELINE, color="0.55", lw=0.9, ls=":", zorder=1)
    axr.annotate(f"baseline {BASELINE:.2f}%", (x[-1], BASELINE), textcoords="offset points",
                 xytext=(4, 4), ha="right", va="bottom", fontsize=8, color="0.45")
    for xi, w in zip(x, wacc):
        if w is not None:
            axr.annotate(f"{w:.2f}%", (xi, w), textcoords="offset points", xytext=(0, -14),
                         ha="center", fontsize=8.5, color=ORANGE)

    axp.set_xticks(x)
    axp.set_xticklabels(labels)
    axp.set_xlim(-0.4, len(x) - 0.6)
    # headroom so annotations don't clip
    pr_lo, pr_hi = min(prices), max(prices)
    axp.set_ylim(pr_lo - (pr_hi - pr_lo) * 0.18 - 5, pr_hi + (pr_hi - pr_lo) * 0.22 + 5)
    wv = [w for w in wacc if w is not None]
    axr.set_ylim(min(wv) - (max(wv) - min(wv)) * 0.55 - 0.2, max(BASELINE, max(wv)) + 0.25)

    FIGS.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(FIGS / "fig_price_path.pdf")
    fig.savefig(FIGS / "fig_price_path.png")

    # macros
    last = closes[-1]
    last_cap_t = float(last["close"]) * sh / 1e6
    last_w = implied_pct(float(last["close"]) * sh)
    L = ["% Auto-generated by 10_fig_price_path.py; do not edit by hand.",
         f"\\newcommand{{\\ppFirstDate}}{{June 12}}",
         f"\\newcommand{{\\ppLastDate}}{{{fmt(last['date'])}}}",
         f"\\newcommand{{\\ppNDays}}{{{len(closes)}}}",
         f"\\newcommand{{\\ppLatestPrice}}{{{float(last['close']):.2f}}}",
         f"\\newcommand{{\\ppLatestCapT}}{{{last_cap_t:.2f}}}",
         f"\\newcommand{{\\ppLatestWaccPct}}{{{last_w:.2f}}}",
         f"\\newcommand{{\\ppLatestErpPp}}{{{last_w - RF:.2f}}}",
         f"\\newcommand{{\\ppOfferWaccPct}}{{{implied_pct(offer * sh):.2f}}}"]
    OUT_TEX.write_text("\n".join(L) + "\n", encoding="utf-8")

    print(f"path ({len(prices)} points incl. offer):")
    for lab, p, w in zip(labels, prices, wacc):
        print(f"  {lab:<8} ${p:>7.2f}  implied {w:.2f}%" if w else f"  {lab:<8} ${p:>7.2f}  --")
    print("Figure:", FIGS / "fig_price_path.pdf")
    print("Macros:", OUT_TEX)


if __name__ == "__main__":
    main()
